### ISSUE TITLE
Add details about changing default WP admin password

### ISSUE THREAD

**Issue by jchou1271** [WordPress-Phoenix/local-wordpress-developent#6]
These DB connections details did not work for me.
MySQL Host: 127.0.0.1
User: 		wp
Pass: 		wp
Database: 	vvv.dev
Port: 		3306
SSH Host: 	vvv.dev
SSH User: 	vagrant
SSH Pass: 	vagrant
SSH Port: 	(none)
Unchecked SSL box

I sshed into the VM, and connected to mysql.  Here are the DBs:
MariaDB [(none)]> show databases;
+----------------------+
| Database             |
+----------------------+
| information_schema   |
| mylocalsitedev       |
| mysql                |
| performance_schema   |
| wordpress_develop    |
| wordpress_unit_tests |
| wordpressdefault     |
+----------------------+
7 rows in set (0.00 sec)

These DB connection details worked:
MySQL Host: 127.0.0.1
User: 		root
Pass: 		root
Database: 	mylocalsitedev
Port: 		3306
SSH Host: 	vvv.dev
SSH User: 	vagrant
SSH Pass: 	vagrant
SSH Port: 	(none)
Unchecked SSL box

Then followed https://www.shoutmeloud.com/how-to-change-wordpress-default-username-security.html to change default WP admin password.

**Comment by scarstens** [comment]
These are really 2 issues, I'll address them seperately:
the credentials wp/wp only work to give you access to the WordPress database. I'm not sure why we logged to connect to a db called vvv.dev (there will never be a db called that, the db actually doesn't need entered, and you can select one after you login on sequel pro). switching back to wp/wp should work fine, I'll update that to empty in the instructions.

**Comment by scarstens** [comment]
regarding changing the admin username and password, you don't need to change the default username and password (which is admin and password) because this is a local only install. I leave this alone, and it's the default of all VVV instances that don't have some custom config. Leaving it defaulted to admin/password keeps the env. consistent across all machines which is important in local development.
